name: Bug report
description: Create a report to help us improve
title: "bug: "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: description
  attributes:
    label: Describe the bug
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  id: reproduction
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the bug you experienced
    placeholder: 1. asdf firebase --version
  validations:
    required: true
- type: input
  id: asdf-firebase-version
  attributes:
    label: asdf-firebase version
    description: What version of `asdf-firebase` are you running?
    placeholder: 1.0.0
  validations:
    required: true
- type: input
  id: firebase-version
  attributes:
    label: firebase version
    description: What version of `firebase` are you running?
    placeholder: 9.16.0
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: Additional Information
    description: Is there more information you would like to share?

# - type: checkboxes
#   id: terms
#   attributes:
#     label: Code of Conduct
#     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#     options:
#       - label: I agree to follow this project's Code of Conduct
#         required: true
