name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Shellcheck
        run: shellcheck -x bin/* -P lib/

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Shell Format - List files to check
        run: shfmt -f .
      - name: Shell Format - Validate
        run: shfmt -d .
